-- English-language recipe sites for the "More Asian recipes" and "European recipes" shelves.
-- Each site was checked: it answers, and its robots.txt allows KidPoshanBot to read recipe pages. Rights are "not_requested";
-- recipes show the creator's name, a photo credit and a link, and steps are written in KidPoshan's own words (like the Indian sites).
-- Safe to run more than once (a site is added only if its address is not already there). One statement per site: D1 limits compound SELECTs.
INSERT INTO kp_recipe_sources (name, platform, region, area, url, notes, active, crawl_mode, status, world) SELECT 'Rasa Malaysia', 'Website', 'Southeast Asia', 'Malaysia', 'https://rasamalaysia.com/', 'Malaysian and Asian home cooking.', 1, 'auto', 'registered', 'asia' WHERE NOT EXISTS (SELECT 1 FROM kp_recipe_sources WHERE url = 'https://rasamalaysia.com/');
INSERT INTO kp_recipe_sources (name, platform, region, area, url, notes, active, crawl_mode, status, world) SELECT 'Nyonya Cooking', 'Website', 'Southeast Asia', 'Singapore / Malaysia', 'https://www.nyonyacooking.com/', 'Peranakan, Singaporean and Malaysian recipes.', 1, 'auto', 'registered', 'asia' WHERE NOT EXISTS (SELECT 1 FROM kp_recipe_sources WHERE url = 'https://www.nyonyacooking.com/');
INSERT INTO kp_recipe_sources (name, platform, region, area, url, notes, active, crawl_mode, status, world) SELECT 'Hot Thai Kitchen', 'Website', 'Southeast Asia', 'Thailand', 'https://hot-thai-kitchen.com/', 'Thai recipes.', 1, 'auto', 'registered', 'asia' WHERE NOT EXISTS (SELECT 1 FROM kp_recipe_sources WHERE url = 'https://hot-thai-kitchen.com/');
INSERT INTO kp_recipe_sources (name, platform, region, area, url, notes, active, crawl_mode, status, world) SELECT 'Panlasang Pinoy', 'Website', 'Southeast Asia', 'Philippines', 'https://panlasangpinoy.com/', 'Filipino recipes.', 1, 'auto', 'registered', 'asia' WHERE NOT EXISTS (SELECT 1 FROM kp_recipe_sources WHERE url = 'https://panlasangpinoy.com/');
INSERT INTO kp_recipe_sources (name, platform, region, area, url, notes, active, crawl_mode, status, world) SELECT 'Kawaling Pinoy', 'Website', 'Southeast Asia', 'Philippines', 'https://www.kawalingpinoy.com/', 'Filipino recipes.', 1, 'auto', 'registered', 'asia' WHERE NOT EXISTS (SELECT 1 FROM kp_recipe_sources WHERE url = 'https://www.kawalingpinoy.com/');
INSERT INTO kp_recipe_sources (name, platform, region, area, url, notes, active, crawl_mode, status, world) SELECT 'Viet World Kitchen', 'Website', 'Southeast Asia', 'Vietnam', 'https://www.vietworldkitchen.com/', 'Vietnamese recipes.', 1, 'auto', 'registered', 'asia' WHERE NOT EXISTS (SELECT 1 FROM kp_recipe_sources WHERE url = 'https://www.vietworldkitchen.com/');
INSERT INTO kp_recipe_sources (name, platform, region, area, url, notes, active, crawl_mode, status, world) SELECT 'Roti n Rice', 'Website', 'Southeast Asia', 'Malaysia / Singapore', 'https://rotinrice.com/', 'Malaysian and Singaporean home cooking.', 1, 'auto', 'registered', 'asia' WHERE NOT EXISTS (SELECT 1 FROM kp_recipe_sources WHERE url = 'https://rotinrice.com/');
INSERT INTO kp_recipe_sources (name, platform, region, area, url, notes, active, crawl_mode, status, world) SELECT 'Malaysian Chinese Kitchen', 'Website', 'Southeast Asia', 'Malaysia', 'https://www.malaysianchinesekitchen.com/', 'Malaysian Chinese home cooking.', 1, 'auto', 'registered', 'asia' WHERE NOT EXISTS (SELECT 1 FROM kp_recipe_sources WHERE url = 'https://www.malaysianchinesekitchen.com/');
INSERT INTO kp_recipe_sources (name, platform, region, area, url, notes, active, crawl_mode, status, world) SELECT 'Greedy Gourmet', 'Website', 'Europe', 'United Kingdom', 'https://www.greedygourmet.com/', 'Family-friendly recipes from a UK-based cook.', 1, 'auto', 'registered', 'europe' WHERE NOT EXISTS (SELECT 1 FROM kp_recipe_sources WHERE url = 'https://www.greedygourmet.com/');
INSERT INTO kp_recipe_sources (name, platform, region, area, url, notes, active, crawl_mode, status, world) SELECT 'Lazy Cat Kitchen', 'Website', 'Europe', 'Germany', 'https://www.lazycatkitchen.com/', 'Plant-based family recipes from Berlin.', 1, 'auto', 'registered', 'europe' WHERE NOT EXISTS (SELECT 1 FROM kp_recipe_sources WHERE url = 'https://www.lazycatkitchen.com/');
INSERT INTO kp_recipe_sources (name, platform, region, area, url, notes, active, crawl_mode, status, world) SELECT 'Annabel Karmel', 'Website', 'Europe', 'United Kingdom', 'https://www.annabelkarmel.com/', 'Baby, toddler and children''s recipes.', 1, 'auto', 'registered', 'europe' WHERE NOT EXISTS (SELECT 1 FROM kp_recipe_sources WHERE url = 'https://www.annabelkarmel.com/');
INSERT INTO kp_recipe_sources (name, platform, region, area, url, notes, active, crawl_mode, status, world) SELECT 'Easy Peasy Foodie', 'Website', 'Europe', 'United Kingdom', 'https://www.easypeasyfoodie.com/', 'Quick family dinners.', 1, 'auto', 'registered', 'europe' WHERE NOT EXISTS (SELECT 1 FROM kp_recipe_sources WHERE url = 'https://www.easypeasyfoodie.com/');
INSERT INTO kp_recipe_sources (name, platform, region, area, url, notes, active, crawl_mode, status, world) SELECT 'Baby Led Weaning Ideas', 'Website', 'Europe', 'United Kingdom', 'https://babyledweaningideas.com/', 'First foods and baby-led weaning recipes.', 1, 'auto', 'registered', 'europe' WHERE NOT EXISTS (SELECT 1 FROM kp_recipe_sources WHERE url = 'https://babyledweaningideas.com/');
