name = "kidposhan-platform"
main = "src/index.js"
compatibility_date = "2026-09-14"

[assets]
directory = "./public"
binding = "ASSETS"
run_worker_first = ["/api/*"]

[[d1_databases]]
binding = "DB"
database_name = "kidposhan-platform-db"
database_id = "0320ade1-1c4f-43eb-8f77-be63da87621c"

[[r2_buckets]]
binding = "MEDIA"
bucket_name = "kidposhan-platform-media"
