-- KidPoshan Recipe Source Registry v2 seed
-- Generated from KidPoshan_Recipe_Source_Registry_v2.xlsx
-- Safe to rerun: INSERT OR IGNORE prevents duplicate source records.

INSERT OR IGNORE INTO recipe_sources (id, source_name, platform, creator_type, region, state_or_area, kids_focus, source_url, notes, active, created_at, updated_at) VALUES ('src_c38dab8ea77b2995e4f0507c', 'Aarthi / Yummy Tummy Aarthi', 'Website', 'Recipe Creator', 'South', 'Tamil Nadu', 'Yes', 'https://www.yummytummyaarthi.com/kids-lunch-box-recipes/', 'Strong South India source; collection says mostly South Indian, North Indian and easy-to-pack menus.', 1, unixepoch(), unixepoch());
INSERT OR IGNORE INTO recipe_sources (id, source_name, platform, creator_type, region, state_or_area, kids_focus, source_url, notes, active, created_at, updated_at) VALUES ('src_3e76d4eaa0a02a354f3b137e', 'Chitra''s Food Book', 'Website', 'Recipe Creator', 'South', 'Tamil Nadu', 'Yes', 'https://chitrasfoodbook.com/kids-recipes-list-breakfastlunch-box/', 'Strong Tamil/South representation.', 1, unixepoch(), unixepoch());
INSERT OR IGNORE INTO recipe_sources (id, source_name, platform, creator_type, region, state_or_area, kids_focus, source_url, notes, active, created_at, updated_at) VALUES ('src_2b8b7a749a51958e1b8729ff', 'Gayatri Vantillu', 'Website', 'Recipe Creator', 'South', 'Andhra Pradesh / Telugu', 'Yes', 'https://www.gayatrivantillu.com/recipes-2/miscellaneous/lunch-box', 'Useful Telugu/Andhra source.', 1, unixepoch(), unixepoch());
INSERT OR IGNORE INTO recipe_sources (id, source_name, platform, creator_type, region, state_or_area, kids_focus, source_url, notes, active, created_at, updated_at) VALUES ('src_0074fabaafb8b519f722fc4e', 'Awesome Cuisine / Praveen Kumar', 'Website', 'Recipe Creator', 'South', 'South India', 'Yes', 'https://www.awesomecuisine.com/recipes/36011/lunch-box-recipes-south-indian/', 'Broad South Indian coverage.', 1, unixepoch(), unixepoch());
INSERT OR IGNORE INTO recipe_sources (id, source_name, platform, creator_type, region, state_or_area, kids_focus, source_url, notes, active, created_at, updated_at) VALUES ('src_5ce7d87b8e04634c2c86a1c9', 'Archana''s Kitchen', 'Website', 'Recipe Platform', 'South / Pan-India', 'India', 'Yes', 'https://www.archanaskitchen.com/collection/kids-lunch-box-ideas-chow-chow-kootu-tawa-paratha-kala-chana-salad-curd', 'Multi-region recipe pool.', 1, unixepoch(), unixepoch());
INSERT OR IGNORE INTO recipe_sources (id, source_name, platform, creator_type, region, state_or_area, kids_focus, source_url, notes, active, created_at, updated_at) VALUES ('src_b2f6e0f2b9ce4e5f44f9d1da', 'SouthIndianRecipes.in', 'Website', 'Recipe Platform', 'South', 'South India', 'Yes', 'https://southindianrecipes.in/lunch-ideas-for-kids-south-indian-recipes/', 'Dedicated South Indian kids content.', 1, unixepoch(), unixepoch());
INSERT OR IGNORE INTO recipe_sources (id, source_name, platform, creator_type, region, state_or_area, kids_focus, source_url, notes, active, created_at, updated_at) VALUES ('src_ee940337edabf965cc409d45', 'Madhu''s Everyday Indian / Madhavi Kadaba', 'Website', 'Recipe Creator', 'South / Pan-India', 'India', 'Yes', 'https://www.madhuseverydayindian.com/kids-lunch-box-recipes-indian/', 'Mostly vegetarian; some vegan and egg recipes.', 1, unixepoch(), unixepoch());
INSERT OR IGNORE INTO recipe_sources (id, source_name, platform, creator_type, region, state_or_area, kids_focus, source_url, notes, active, created_at, updated_at) VALUES ('src_0ffa8d3224518fbbce3b69ea', 'Vidhya''s Home Cooking / Srividhya', 'Website', 'Recipe Creator', 'South', 'South India', 'Yes', 'https://www.vidhyashomecooking.com/ghee-rice-with-veggies-and-paneer-ghee-bhath/', 'Useful South Indian family-recipe source.', 1, unixepoch(), unixepoch());
INSERT OR IGNORE INTO recipe_sources (id, source_name, platform, creator_type, region, state_or_area, kids_focus, source_url, notes, active, created_at, updated_at) VALUES ('src_1448069e8cb10bf143c40bbe', 'Nitha Kitchen / Sangeetha Priya', 'Website', 'Recipe Creator', 'South', 'Tamil Nadu / South India', 'Yes', 'https://www.nithaskitchen.com/2024/03/south-indian-lunch-box-recipe-idea-1.html', 'Explicit school lunchbox series.', 1, unixepoch(), unixepoch());
INSERT OR IGNORE INTO recipe_sources (id, source_name, platform, creator_type, region, state_or_area, kids_focus, source_url, notes, active, created_at, updated_at) VALUES ('src_24885a720319b7841b0a433f', 'Indian Veggie Delight / Bhavana Patil', 'Website', 'Recipe Creator', 'Pan-India', 'India', 'Yes', 'https://www.indianveggiedelight.com/healthy-kids-lunch-box-recipes-indian/', 'Large recipe pool; score independently.', 1, unixepoch(), unixepoch());
INSERT OR IGNORE INTO recipe_sources (id, source_name, platform, creator_type, region, state_or_area, kids_focus, source_url, notes, active, created_at, updated_at) VALUES ('src_25e27506e3056ccc9a409906', 'Pankaj Bhadouria', 'Web / Media', 'Chef', 'Pan-India', 'India', 'Yes', 'https://www.aajtak.in/lifestyle/kitchen/story/lunchbox-recipes-for-kids-tiffin-by-masterchef-pankaj-bhadouria-pav-bhaji-boats-korean-corn-dogs-soya-chunks-guaranteed-empty-return-tvist-dskc-2492433-2026-03-12', 'Chef source; recipes scored independently.', 1, unixepoch(), unixepoch());
INSERT OR IGNORE INTO recipe_sources (id, source_name, platform, creator_type, region, state_or_area, kids_focus, source_url, notes, active, created_at, updated_at) VALUES ('src_9e61dea96174818485e3ba55', 'Sanjeev Kapoor', 'Web / Media', 'Chef', 'Pan-India', 'India', 'Yes', 'https://www.hindustantimes.com/lifestyle/recipe/out-of-school-tiffin-ideas-for-your-child-chef-sanjeev-kapoors-soya-keema-frankie-recipe-is-perfect-for-busy-mornings-101785565856353.html', 'Chef source.', 1, unixepoch(), unixepoch());
INSERT OR IGNORE INTO recipe_sources (id, source_name, platform, creator_type, region, state_or_area, kids_focus, source_url, notes, active, created_at, updated_at) VALUES ('src_efeca56532631d7b97ff1549', 'FirstCry Parenting', 'Website', 'Publication / Recipe Platform', 'Pan-India', 'India', 'Yes', 'https://parenting.firstcry.com/articles/10-amazing-kids-lunch-box-ideas/', 'Useful large kids-focused source.', 1, unixepoch(), unixepoch());
INSERT OR IGNORE INTO recipe_sources (id, source_name, platform, creator_type, region, state_or_area, kids_focus, source_url, notes, active, created_at, updated_at) VALUES ('src_bf73907ac42e66c0130dded2', 'NDTV Food', 'Website', 'Publication / Recipe Platform', 'Pan-India', 'India', 'Yes', 'https://food.ndtv.com/food-drinks/what-to-pack-in-the-tiffin-try-these-7-regional-indian-lunchbox-recipes-9039784', 'Useful regional discovery source.', 1, unixepoch(), unixepoch());
INSERT OR IGNORE INTO recipe_sources (id, source_name, platform, creator_type, region, state_or_area, kids_focus, source_url, notes, active, created_at, updated_at) VALUES ('src_d686bbf0276ec4ce87e59dfe', 'Kidsstoppress / Mariyam Lamak Kanchwala', 'Website', 'Recipe Creator / Publication', 'Pan-India', 'India', 'Yes', 'https://kidsstoppress.com/indian-lunchbox-recipes-for-kids/', 'Creator is a food/lifestyle blogger and recipe curator.', 1, unixepoch(), unixepoch());
INSERT OR IGNORE INTO recipe_sources (id, source_name, platform, creator_type, region, state_or_area, kids_focus, source_url, notes, active, created_at, updated_at) VALUES ('src_f565799f32070e21565888a5', 'Pooja Makhija', 'Web / Media', 'Nutritionist / Recipe Creator', 'Pan-India', 'India', 'Yes', 'https://food.ndtv.com/food-drinks/can-t-get-your-kids-to-eat-roti-try-this-easy-and-yummy-recipe-by-pooja-makhija-2470556', 'Use recipes as source material; creator credentials do not affect score.', 1, unixepoch(), unixepoch());
INSERT OR IGNORE INTO recipe_sources (id, source_name, platform, creator_type, region, state_or_area, kids_focus, source_url, notes, active, created_at, updated_at) VALUES ('src_6b885317507fac31647dc70e', 'Rujuta Diwekar', 'Web / Media', 'Nutritionist / Author', 'Pan-India', 'India', 'Yes', 'https://www.ndtv.com/book-excerpts/making-indian-kids-eat-healthy-by-rujuta-diwekar-1972691', 'Use recipe/meal ideas; score independently.', 1, unixepoch(), unixepoch());
INSERT OR IGNORE INTO recipe_sources (id, source_name, platform, creator_type, region, state_or_area, kids_focus, source_url, notes, active, created_at, updated_at) VALUES ('src_26542000bdb16c3674a616b0', 'NorthIndianFood.in', 'Website', 'Recipe Platform', 'North', 'North India', 'Yes', 'https://northindianfood.in/indian-lunch-box-ideas-without-reheating/', 'Adds North Indian representation.', 1, unixepoch(), unixepoch());
INSERT OR IGNORE INTO recipe_sources (id, source_name, platform, creator_type, region, state_or_area, kids_focus, source_url, notes, active, created_at, updated_at) VALUES ('src_d4a863d829ae4dfa3dd2fbd6', 'Kabita''s Kitchen / Kabita Singh', 'YouTube / Social', 'Chef / Recipe Creator', 'North / Pan-India', 'India', 'Yes', 'https://www.youtube.com/results?search_query=Kabita%27s+Kitchen+kids+lunchbox', 'Large recipe creator; include individual recipes after screening.', 1, unixepoch(), unixepoch());
INSERT OR IGNORE INTO recipe_sources (id, source_name, platform, creator_type, region, state_or_area, kids_focus, source_url, notes, active, created_at, updated_at) VALUES ('src_cbab5311a16bbebb1cd01336', 'Good to Eat - Odia', 'YouTube', 'Recipe Creator', 'East', 'Odisha', 'Yes', 'https://www.youtube.com/watch?v=BQ_qDbtsVDg', 'Strong Odisha source; verified channel and explicit kids tiffin content.', 1, unixepoch(), unixepoch());
INSERT OR IGNORE INTO recipe_sources (id, source_name, platform, creator_type, region, state_or_area, kids_focus, source_url, notes, active, created_at, updated_at) VALUES ('src_d04f5dd256a29bdf3f9c8674', 'Oriyarasoi', 'Website', 'Recipe Creator', 'East', 'Odisha', 'Yes', 'https://www.oriyarasoi.com/search/label/100%20kids%20lunch%20box%20recipes', 'Strong Odisha source with kid-specific collection.', 1, unixepoch(), unixepoch());
INSERT OR IGNORE INTO recipe_sources (id, source_name, platform, creator_type, region, state_or_area, kids_focus, source_url, notes, active, created_at, updated_at) VALUES ('src_067c48d7e1869779cc0978d9', 'Alka Jena / Culinary Xpress', 'Website', 'Recipe Creator', 'East', 'Odisha', 'Family / General', 'https://www.archanaskitchen.com/author/alka-jena', 'Food blogger/recipe developer based in Bhubaneswar; use suitable recipes after child screening.', 1, unixepoch(), unixepoch());
INSERT OR IGNORE INTO recipe_sources (id, source_name, platform, creator_type, region, state_or_area, kids_focus, source_url, notes, active, created_at, updated_at) VALUES ('src_ad2f3b431d5572322a040b92', 'Minakshi''s Kitchen', 'Website', 'Recipe Creator', 'East', 'Odisha', 'Family / General', 'https://minakshikitchen.blogspot.com/', 'Odia recipe source; screen individual recipes for child suitability.', 1, unixepoch(), unixepoch());
INSERT OR IGNORE INTO recipe_sources (id, source_name, platform, creator_type, region, state_or_area, kids_focus, source_url, notes, active, created_at, updated_at) VALUES ('src_03dbaaa0b39f7e0ce92043ae', 'Bong Eats', 'Website / YouTube', 'Recipe Creator / Culinary Platform', 'East', 'West Bengal', 'Family / General', 'https://www.bongeats.com/recipes/', 'Strong Bengali/Kolkata source; not specifically kids-focused, so screen recipes.', 1, unixepoch(), unixepoch());
INSERT OR IGNORE INTO recipe_sources (id, source_name, platform, creator_type, region, state_or_area, kids_focus, source_url, notes, active, created_at, updated_at) VALUES ('src_7739965cd5db83f25d0be7d5', 'Bong Eats', 'YouTube', 'Recipe Creator / Culinary Platform', 'East', 'West Bengal', 'Family / General', 'https://www.youtube.com/@BongEats', 'Useful video discovery source for Bengali recipes.', 1, unixepoch(), unixepoch());
INSERT OR IGNORE INTO recipe_sources (id, source_name, platform, creator_type, region, state_or_area, kids_focus, source_url, notes, active, created_at, updated_at) VALUES ('src_8ff7ec982b68856a9b6674fe', 'Indian Express Tamil', 'Website', 'Publication / Recipe Platform', 'South', 'Tamil Nadu', 'Yes', 'https://tamil.indianexpress.com/food/', 'Regional discovery source.', 1, unixepoch(), unixepoch());
INSERT OR IGNORE INTO recipe_sources (id, source_name, platform, creator_type, region, state_or_area, kids_focus, source_url, notes, active, created_at, updated_at) VALUES ('src_4a08ffaf853ee334a470d6cb', 'Asianet News Tamil', 'Website', 'Publication / Recipe Platform', 'South', 'Tamil Nadu', 'Yes', 'https://tamil.asianetnews.com/gallery/life-style/easy-and-quick-5-days-5-lunch-box-recipes-in-tamil-kimoipg', 'Tamil regional source.', 1, unixepoch(), unixepoch());
INSERT OR IGNORE INTO recipe_sources (id, source_name, platform, creator_type, region, state_or_area, kids_focus, source_url, notes, active, created_at, updated_at) VALUES ('src_5add84c0f864b7cc04759d76', 'Telugu BoldSky', 'Website', 'Publication / Recipe Platform', 'South', 'Andhra Pradesh / Telangana', 'Yes', 'https://telugu.boldsky.com/recipes/protein-rich-soya-mint-rice-healthy-tasty-lunch-box-recipe-for-kids-in-telugu/', 'Telugu regional discovery source.', 1, unixepoch(), unixepoch());
INSERT OR IGNORE INTO recipe_sources (id, source_name, platform, creator_type, region, state_or_area, kids_focus, source_url, notes, active, created_at, updated_at) VALUES ('src_cf98319a75bbd0b16f9b9de8', 'Slurrp', 'Website', 'Recipe Platform', 'South / Pan-India', 'India', 'Yes', 'https://www.slurrp.com/article/8-amazing-south-indian-style-lunch-box-recipes-kids-will-love-1686736624417', 'Includes Karnataka, Kerala, Tamil Nadu, Andhra, Telangana and Goa/Konkan examples.', 1, unixepoch(), unixepoch());
INSERT OR IGNORE INTO recipe_sources (id, source_name, platform, creator_type, region, state_or_area, kids_focus, source_url, notes, active, created_at, updated_at) VALUES ('src_466ddb206bc9a8c9a334c658', 'theAsianparent India', 'Website', 'Publication / Recipe Platform', 'Pan-India', 'India', 'Yes', 'https://in.theasianparent.com/en/feeding-nutrition/indian-lunch-box-recipes', 'Pan-India discovery source.', 1, unixepoch(), unixepoch());
INSERT OR IGNORE INTO recipe_sources (id, source_name, platform, creator_type, region, state_or_area, kids_focus, source_url, notes, active, created_at, updated_at) VALUES ('src_655a1fa6e28eb5aacca5c39b', 'Mrs YumTum / Instagram', 'Instagram', 'Recipe Creator', 'Pan-India', 'India', 'Yes', 'https://www.instagram.com/mrsyumtum/', 'Instagram discovery source; individual posts to be captured later.', 1, unixepoch(), unixepoch());
INSERT OR IGNORE INTO recipe_sources (id, source_name, platform, creator_type, region, state_or_area, kids_focus, source_url, notes, active, created_at, updated_at) VALUES ('src_e221a512cd45bcd752c52378', 'Shivani Rasoi / Instagram', 'Instagram', 'Recipe Creator', 'Pan-India', 'India', 'Yes', 'https://www.instagram.com/shivanirasoi/', 'High-volume kids lunchbox discovery source.', 1, unixepoch(), unixepoch());
INSERT OR IGNORE INTO recipe_sources (id, source_name, platform, creator_type, region, state_or_area, kids_focus, source_url, notes, active, created_at, updated_at) VALUES ('src_58703891d500fcf700a29496', 'Dhivya Shankari / Instagram', 'Instagram', 'Recipe Creator', 'South', 'Tamil Nadu / South India', 'Yes', 'https://www.instagram.com/dhivya.shankari/', 'Explicit South Indian school lunchbox content.', 1, unixepoch(), unixepoch());
INSERT OR IGNORE INTO recipe_sources (id, source_name, platform, creator_type, region, state_or_area, kids_focus, source_url, notes, active, created_at, updated_at) VALUES ('src_b572310397f5f3a0b100bc36', 'Malabar Menu / Instagram', 'Instagram', 'Recipe Creator', 'South', 'Kerala / Malabar', 'Yes', 'https://www.instagram.com/malabar_menu/', 'Useful Kerala/Malabar representation.', 1, unixepoch(), unixepoch());
INSERT OR IGNORE INTO recipe_sources (id, source_name, platform, creator_type, region, state_or_area, kids_focus, source_url, notes, active, created_at, updated_at) VALUES ('src_45aa20c6926217e5e4eb47db', 'Good Eats by Heena Diwan / Instagram', 'Instagram', 'Recipe Creator', 'Pan-India', 'India', 'Yes', 'https://www.instagram.com/good_eats_by_heena_diwan/', 'Kids-focused Instagram discovery source.', 1, unixepoch(), unixepoch());
INSERT OR IGNORE INTO recipe_sources (id, source_name, platform, creator_type, region, state_or_area, kids_focus, source_url, notes, active, created_at, updated_at) VALUES ('src_a0a275c889f35c858fffc78c', 'A_M_K_Cookbook / Instagram', 'Instagram', 'Recipe Creator', 'Pan-India', 'India', 'Yes', 'https://www.instagram.com/a_m_k_cookbook/', 'Instagram discovery source.', 1, unixepoch(), unixepoch());
INSERT OR IGNORE INTO recipe_sources (id, source_name, platform, creator_type, region, state_or_area, kids_focus, source_url, notes, active, created_at, updated_at) VALUES ('src_a6a5018f403de43fd05fff9b', 'Culinary Chaser / Instagram', 'Instagram', 'Recipe Creator', 'Pan-India', 'India', 'Yes', 'https://www.instagram.com/culinarychaser/', 'Family/lunchbox discovery source.', 1, unixepoch(), unixepoch());
INSERT OR IGNORE INTO recipe_sources (id, source_name, platform, creator_type, region, state_or_area, kids_focus, source_url, notes, active, created_at, updated_at) VALUES ('src_aff5871673ecd1c16404de5c', 'Samaipom Sindhipom / Instagram', 'Instagram', 'Recipe Creator', 'South', 'Tamil / South Indian', 'Yes', 'https://www.instagram.com/samaipomsindhipom/', 'South Indian discovery source.', 1, unixepoch(), unixepoch());
INSERT OR IGNORE INTO recipe_sources (id, source_name, platform, creator_type, region, state_or_area, kids_focus, source_url, notes, active, created_at, updated_at) VALUES ('src_8c70d097703057cc4c281c41', 'Vidhyusdecor / Instagram', 'Instagram', 'Recipe Creator', 'Pan-India', 'India', 'Yes', 'https://www.instagram.com/vidyusdecor/', 'Family lunchbox discovery source.', 1, unixepoch(), unixepoch());
