PRAGMA foreign_keys = ON;

INSERT OR IGNORE INTO users(id,email,mobile,name,password_hash,password_salt,password_iterations,role,created_at)
VALUES('demo-admin','admin@kidposhan.local','9999999999','KidPoshan Admin',NULL,NULL,NULL,'admin',strftime('%s','now'));

INSERT OR IGNORE INTO media_assets(id,url,alt_text,kind,status,created_at,updated_at) VALUES
('img-aloo','/assets/images/aloo-tikki.jpg','Aloo Tikki','recipe','published',strftime('%s','now'),strftime('%s','now')),
('img-ragi','/assets/images/ragi-bites.jpg','Ragi Energy Bites','recipe','published',strftime('%s','now'),strftime('%s','now')),
('img-paneer','/assets/images/paneer-toast.jpg','Paneer and Peas Toast','recipe','published',strftime('%s','now'),strftime('%s','now')),
('img-khichdi','/assets/images/veg-khichdi.jpg','Vegetable Khichdi','recipe','published',strftime('%s','now'),strftime('%s','now')),
('img-cookies','/assets/images/carrot-cookies.jpg','Carrot Oat Cookies','recipe','published',strftime('%s','now'),strftime('%s','now')),
('img-apple','/assets/images/apple-oats.jpg','Apple Cinnamon Oats','recipe','published',strftime('%s','now'),strftime('%s','now')),
('img-beet','/assets/images/beetroot-cutlet.jpg','Beetroot Cutlet','recipe','published',strftime('%s','now'),strftime('%s','now'));

INSERT OR IGNORE INTO recipes(id,slug,name,description,image_media_id,score,age_min,age_max,meal_moment,season,diet,prep_minutes,difficulty,ingredients_json,method_json,nutrition_json,benefits_json,serve_with_json,tags_json,status,created_at,updated_at) VALUES
('r-aloo','aloo-tikki','Aloo Tikki','Crispy outside, soft inside. A tasty and nutritious snack that kids love.','img-aloo',88,5,8,'4 PM Snack','Winter','Veg',20,'Easy','[{"name":"Potatoes (boiled and mashed)","qty":"3 medium (300 g)","key":"potatoes"},{"name":"Green peas (boiled)","qty":"½ cup (75 g)","key":"peas"},{"name":"Carrot (grated)","qty":"½ cup (50 g)","key":"carrot"},{"name":"Green chilli (finely chopped)","qty":"½ tsp, optional","key":"green chilli"},{"name":"Coriander leaves (chopped)","qty":"2 tbsp","key":"coriander"},{"name":"Jeera (cumin) powder","qty":"½ tsp","key":"cumin"},{"name":"Garam masala","qty":"¼ tsp","key":"garam masala"},{"name":"Salt","qty":"to taste","key":"salt"},{"name":"Oil (for shallow frying)","qty":"2 tbsp","key":"oil"}]','[{"title":"Prepare the vegetables","text":"Boil the potatoes and peas until tender. Mash the potatoes until mostly smooth and grate the carrot finely."},{"title":"Make the mixture","text":"Combine potato, peas, carrot, coriander, cumin, garam masala and a small amount of salt. Mix until the mixture holds together when pressed."},{"title":"Shape the tikkis","text":"Divide into small portions and flatten gently into palm-sized discs. Keep them slightly thick so they stay soft inside."},{"title":"Cook until golden","text":"Heat a non-stick pan on medium heat. Brush with a little oil and cook the tikkis for 3–4 minutes per side until golden and crisp."},{"title":"Cool and serve","text":"Let them cool briefly before serving. Offer with plain yoghurt, mint chutney or a mild tomato dip."}]','{"calories":130,"carbohydrates":"22 g","protein":"3 g","fat":"4 g","fibre":"4 g"}','["Provides energy and keeps them full","Good source of fibre and potassium","Uses familiar vegetables","Works well as an afternoon snack"]','["Plain yoghurt","Mint chutney","Mild tomato dip","Cucumber sticks"]','["winter","snack","vegetarian","kid-friendly"]','published',strftime('%s','now'),strftime('%s','now')),
('r-ragi','ragi-energy-bites','Ragi Energy Bites','No-cook, nutrient-dense bites with ragi, dates and nuts.','img-ragi',88,5,8,'4 PM Snack','Winter','Veg',10,'Easy','[{"name":"Ragi flour","qty":"1 cup","key":"ragi flour"},{"name":"Soft dates, deseeded","qty":"½ cup","key":"dates"},{"name":"Nut powder","qty":"¼ cup","key":"nuts"},{"name":"Ghee","qty":"1 tsp, optional","key":"ghee"}]','[{"title":"Check the dates","text":"Use soft, deseeded dates. If they are firm, soak them in warm water for 5 minutes and drain well."},{"title":"Blend the base","text":"Blend dates and nut powder until they form a sticky, mouldable mixture."},{"title":"Add ragi","text":"Add ragi flour gradually and mix. If the mixture feels dry, add a teaspoon of ghee."},{"title":"Shape the bites","text":"Pinch off small portions and roll between your palms into bite-sized balls."},{"title":"Rest and store","text":"Let the bites rest for 10 minutes before serving. Store covered and use within a short period."}]','{"calories":110,"protein":"3 g","fibre":"3 g"}','["No-cook preparation","Convenient portable snack","Contains ragi and nuts","Naturally sweet from dates"]','["Milk","Fresh fruit","Plain yoghurt"]','["winter","snack","vegetarian"]','published',strftime('%s','now'),strftime('%s','now')),
('r-paneer','paneer-peas-toast','Paneer & Peas Toast','Protein-rich, tasty and quick to make.','img-paneer',86,5,8,'4 PM Snack','Winter','Veg',10,'Easy','[{"name":"Wholegrain bread","qty":"2 slices","key":"bread"},{"name":"Paneer","qty":"50 g, crumbled","key":"paneer"},{"name":"Green peas","qty":"¼ cup, cooked","key":"peas"},{"name":"Cumin powder","qty":"¼ tsp","key":"cumin"},{"name":"Oil or ghee","qty":"½ tsp","key":"oil"}]','[{"title":"Prepare the filling","text":"Mash the cooked peas lightly and combine with crumbled paneer and cumin powder."},{"title":"Season gently","text":"Mix well and taste. Keep seasoning mild for children."},{"title":"Assemble","text":"Spread the paneer-and-peas mixture evenly over the bread slices."},{"title":"Toast","text":"Heat a pan or sandwich toaster and cook until the bread is crisp and the filling is hot."},{"title":"Cut and serve","text":"Cool for a minute, cut into strips or small squares, and serve."}]','{"calories":180,"protein":"8 g","fibre":"4 g"}','["Protein-rich","Quick to prepare","Easy to pack for school","Includes a vegetable"]','["Cucumber","Plain yoghurt","Fruit"]','["winter","snack","vegetarian"]','published',strftime('%s','now'),strftime('%s','now')),
('r-khichdi','vegetable-khichdi','Vegetable Khichdi','A wholesome, easy-to-digest one-pot meal with vegetables and dal.','img-khichdi',83,2,8,'Lunch','All Seasons','Veg',25,'Easy','[{"name":"Rice","qty":"½ cup","key":"rice"},{"name":"Moong dal","qty":"¼ cup","key":"moong dal"},{"name":"Mixed vegetables","qty":"1 cup, finely chopped","key":"vegetables"},{"name":"Turmeric","qty":"a pinch","key":"turmeric"},{"name":"Ghee","qty":"1 tsp, optional","key":"ghee"},{"name":"Water","qty":"2½–3 cups","key":"water"}]','[{"title":"Wash and soak","text":"Rinse the rice and moong dal well. Soak for 10 minutes if time allows."},{"title":"Prepare the vegetables","text":"Use soft vegetables such as carrot, peas, pumpkin or beans. Chop them finely for an even texture."},{"title":"Combine","text":"Add rice, dal, vegetables, turmeric and water to a pressure cooker or heavy pot."},{"title":"Cook until soft","text":"Cook until the rice, dal and vegetables are very soft. For younger children, make the consistency slightly more porridge-like."},{"title":"Finish and serve","text":"Stir well, add a little ghee if desired, cool to a safe temperature and serve."}]','{"calories":220,"protein":"8 g","fibre":"5 g"}','["Soft texture","Easy to digest","One-pot meal","Vegetable-rich"]','["Plain yoghurt","A little ghee","Soft fruit"]','["lunch","vegetarian"]','published',strftime('%s','now'),strftime('%s','now')),
('r-cookies','carrot-oat-cookies','Carrot Oat Cookies','Healthy, naturally sweet and kid-friendly.','img-cookies',80,5,8,'4 PM Snack','All Seasons','Veg',20,'Easy','[{"name":"Oats","qty":"1 cup, ground","key":"oats"},{"name":"Carrot","qty":"½ cup, finely grated","key":"carrot"},{"name":"Ripe banana","qty":"1 medium, mashed","key":"banana"},{"name":"Cinnamon","qty":"¼ tsp","key":"cinnamon"}]','[{"title":"Heat the oven","text":"Preheat the oven to 175°C and line a baking tray with baking paper."},{"title":"Prepare the wet ingredients","text":"Mash the ripe banana until smooth. Stir in the finely grated carrot and cinnamon."},{"title":"Add oats","text":"Mix in the ground oats until a soft, scoopable dough forms. Let it stand for 5 minutes."},{"title":"Shape","text":"Scoop small portions onto the tray and flatten gently with the back of a spoon."},{"title":"Bake and cool","text":"Bake for about 12–15 minutes until set and lightly golden. Cool completely before serving."}]','{"calories":120,"protein":"3 g","fibre":"3 g"}','["Naturally sweet","Fibre-rich","Simple ingredients","Easy lunchbox option"]','["Milk","Fruit","Plain yoghurt"]','["snack","vegetarian"]','published',strftime('%s','now'),strftime('%s','now')),
('r-apple','apple-cinnamon-oats','Apple Cinnamon Oats','Warm, comforting and full of fibre.','img-apple',82,2,8,'Breakfast','Winter','Veg',15,'Easy','[{"name":"Oats","qty":"½ cup","key":"oats"},{"name":"Apple","qty":"1 small, finely diced","key":"apple"},{"name":"Milk","qty":"1 cup","key":"milk"},{"name":"Cinnamon","qty":"a small pinch","key":"cinnamon"},{"name":"Water","qty":"½ cup, as needed","key":"water"}]','[{"title":"Prepare the apple","text":"Wash, peel if needed, and dice the apple into small pieces."},{"title":"Start the oats","text":"Add oats, milk and water to a saucepan. Cook on low-medium heat, stirring regularly."},{"title":"Add the apple","text":"Stir in the diced apple and continue cooking until the oats are soft and the apple is tender."},{"title":"Finish","text":"Add a small pinch of cinnamon and adjust the consistency with a little warm water or milk."},{"title":"Cool and serve","text":"Allow the bowl to cool to a comfortable temperature before serving."}]','{"calories":190,"protein":"6 g","fibre":"4 g"}','["Warm breakfast","Fibre-rich","Soft texture","Easy to customise"]','["Banana","Plain yoghurt","Nut powder if age-appropriate"]','["breakfast","winter","vegetarian"]','published',strftime('%s','now'),strftime('%s','now')),
('r-beet','beetroot-cutlet','Beetroot Cutlet','Colourful, nutritious and loved by kids.','img-beet',76,5,8,'4 PM Snack','Winter','Veg',25,'Medium','[{"name":"Beetroot","qty":"1 medium, cooked","key":"beetroot"},{"name":"Potato","qty":"2 medium, boiled","key":"potatoes"},{"name":"Breadcrumbs or oat powder","qty":"2 tbsp","key":"crumbs"},{"name":"Cumin powder","qty":"¼ tsp","key":"cumin"},{"name":"Oil","qty":"1 tbsp","key":"oil"}]','[{"title":"Cook the vegetables","text":"Boil or steam the beetroot and potatoes until tender. Cool and remove the skins."},{"title":"Make the mixture","text":"Grate or mash the beetroot and potato. Add breadcrumbs or oat powder and a little cumin."},{"title":"Shape","text":"Mix until the mixture holds together, then shape into small, flat cutlets."},{"title":"Pan-cook","text":"Heat a lightly greased pan and cook the cutlets on medium heat until both sides are firm and lightly crisp."},{"title":"Serve","text":"Cool briefly and serve with plain yoghurt or cucumber."}]','{"calories":100,"protein":"2 g","fibre":"3 g"}','["Colourful","Vegetable-rich","Fun finger-food shape","Good way to introduce beetroot"]','["Plain yoghurt","Cucumber","Fruit"]','["snack","winter","vegetarian"]','published',strftime('%s','now'),strftime('%s','now'));
