PRAGMA foreign_keys = ON;
INSERT OR IGNORE INTO users(id,email,mobile,name,password_hash,password_salt,password_iterations,role,created_at)
VALUES('demo-admin','admin@kidposhan.local','9999999999','KidPoshan Admin',NULL,NULL,NULL,'admin',strftime('%s','now'));

INSERT OR IGNORE INTO media_assets(id,url,alt_text,kind,status,created_at,updated_at) VALUES
('img-aloo','/assets/images/aloo-tikki.jpg','Aloo Tikki','recipe','published',strftime('%s','now'),strftime('%s','now')),
('img-ragi','/assets/images/ragi-bites.jpg','Ragi Energy Bites','recipe','published',strftime('%s','now'),strftime('%s','now')),
('img-paneer','/assets/images/paneer-toast.jpg','Paneer and Peas Toast','recipe','published',strftime('%s','now'),strftime('%s','now')),
('img-khichdi','/assets/images/veg-khichdi.jpg','Vegetable Khichdi','recipe','published',strftime('%s','now'),strftime('%s','now')),
('img-cookies','/assets/images/carrot-cookies.jpg','Carrot Oat Cookies','recipe','published',strftime('%s','now'),strftime('%s','now')),
('img-apple','/assets/images/apple-oats.jpg','Apple Cinnamon Oats','recipe','published',strftime('%s','now'),strftime('%s','now')),
('img-beet','/assets/images/beetroot-cutlet.jpg','Beetroot Cutlet','recipe','published',strftime('%s','now'),strftime('%s','now'));

INSERT OR IGNORE INTO recipes(id,slug,name,description,image_media_id,score,age_min,age_max,meal_moment,season,diet,prep_minutes,difficulty,ingredients_json,method_json,nutrition_json,benefits_json,serve_with_json,tags_json,status,created_at,updated_at) VALUES
('r-aloo','aloo-tikki','Aloo Tikki','Crispy outside, soft inside. A tasty and nutritious snack that kids love.','img-aloo',88,5,8,'4 PM Snack','Winter','Veg',20,'Easy','[{"name":"Potatoes (boiled and mashed)","qty":"3 medium (300 g)","key":"potatoes"},{"name":"Green peas (boiled)","qty":"½ cup (75 g)","key":"peas"},{"name":"Carrot (grated)","qty":"½ cup (50 g)","key":"carrot"},{"name":"Green chilli (finely chopped)","qty":"1 tsp","key":"green chilli"},{"name":"Coriander leaves (chopped)","qty":"2 tbsp","key":"coriander"},{"name":"Jeera (cumin) powder","qty":"½ tsp","key":"cumin"},{"name":"Garam masala","qty":"½ tsp","key":"garam masala"},{"name":"Salt","qty":"to taste","key":"salt"},{"name":"Oil (for shallow frying)","qty":"2 tbsp","key":"oil"}]','[{"title":"Prepare the mixture","text":"Combine mashed potatoes, peas, grated carrot, green chilli, coriander, cumin powder, garam masala and salt."},{"title":"Shape the tikkis","text":"Divide into small portions and shape into flat tikkis."},{"title":"Cook the tikkis","text":"Cook with a little oil on medium heat until golden brown and crisp on both sides."},{"title":"Serve","text":"Serve warm with ketchup, mint chutney or plain yoghurt dip."}]','{"calories":130,"carbohydrates":"22 g","protein":"3 g","fat":"4 g","fibre":"4 g"}','["Provides energy and keeps them full","Good source of fibre and potassium","Easy to make with simple ingredients","Popular 4 PM snack"]','["Mint chutney","Tomato ketchup","Plain yoghurt dip","Cucumber salad"]','["winter","snack","vegetarian","kid-friendly"]','published',strftime('%s','now'),strftime('%s','now')),
('r-ragi','ragi-energy-bites','Ragi Energy Bites','No-cook, nutrient-dense bites with ragi, nuts and dates.','img-ragi',88,5,8,'4 PM Snack','Winter','Veg',10,'Easy','[{"name":"Ragi flour","qty":"1 cup","key":"ragi flour"},{"name":"Dates","qty":"½ cup","key":"dates"},{"name":"Nut powder","qty":"¼ cup","key":"nuts"}]','[{"title":"Blend","text":"Blend dates and nut powder into a sticky mixture."},{"title":"Mix","text":"Add ragi flour and combine well."},{"title":"Shape","text":"Roll into bite-sized balls."}]','{"calories":110,"protein":"3 g","fibre":"3 g"}','["No-cook","Nutrient dense","Portable snack"]','["Milk","Fruit"]','["winter","snack","vegetarian"]','published',strftime('%s','now'),strftime('%s','now')),
('r-paneer','paneer-peas-toast','Paneer & Peas Toast','Protein-rich, tasty and quick to make.','img-paneer',86,5,8,'4 PM Snack','Winter','Veg',10,'Easy','[{"name":"Wholegrain bread","qty":"2 slices","key":"bread"},{"name":"Paneer","qty":"50 g","key":"paneer"},{"name":"Peas","qty":"¼ cup","key":"peas"}]','[{"title":"Mix","text":"Mash paneer and peas together with mild seasoning."},{"title":"Toast","text":"Spread on bread and toast until crisp."}]','{"calories":180,"protein":"8 g","fibre":"4 g"}','["Protein-rich","Quick","School-friendly"]','["Cucumber","Yoghurt"]','["winter","snack","vegetarian"]','published',strftime('%s','now'),strftime('%s','now')),
('r-khichdi','vegetable-khichdi','Vegetable Khichdi','A wholesome, easy-to-digest one-pot meal with vegetables and dal.','img-khichdi',83,2,8,'Lunch','All Seasons','Veg',25,'Easy','[{"name":"Rice","qty":"½ cup","key":"rice"},{"name":"Moong dal","qty":"¼ cup","key":"moong dal"},{"name":"Mixed vegetables","qty":"1 cup","key":"vegetables"}]','[{"title":"Combine","text":"Wash rice and dal and add vegetables."},{"title":"Cook","text":"Cook until soft and creamy."}]','{"calories":220,"protein":"8 g","fibre":"5 g"}','["Easy to digest","One-pot meal","Vegetable-rich"]','["Yoghurt","Ghee"]','["lunch","vegetarian"]','published',strftime('%s','now'),strftime('%s','now')),
('r-cookies','carrot-oat-cookies','Carrot Oat Cookies','Healthy, naturally sweet and kid-friendly.','img-cookies',80,5,8,'4 PM Snack','All Seasons','Veg',20,'Easy','[{"name":"Oats","qty":"1 cup","key":"oats"},{"name":"Carrot","qty":"½ cup","key":"carrot"},{"name":"Banana","qty":"1","key":"banana"}]','[{"title":"Mix","text":"Combine oats, grated carrot and mashed banana."},{"title":"Bake","text":"Bake until set and lightly golden."}]','{"calories":120,"protein":"3 g","fibre":"3 g"}','["Naturally sweet","Fibre-rich"]','["Milk","Fruit"]','["snack","vegetarian"]','published',strftime('%s','now'),strftime('%s','now')),
('r-apple','apple-cinnamon-oats','Apple Cinnamon Oats','Warm, comforting and full of fibre.','img-apple',82,2,8,'Breakfast','Winter','Veg',15,'Easy','[{"name":"Oats","qty":"½ cup","key":"oats"},{"name":"Apple","qty":"1","key":"apple"},{"name":"Milk","qty":"1 cup","key":"milk"}]','[{"title":"Simmer","text":"Cook oats with milk and diced apple."},{"title":"Finish","text":"Add cinnamon and serve warm."}]','{"calories":190,"protein":"6 g","fibre":"4 g"}','["Warm breakfast","Fibre-rich"]','["Banana","Yoghurt"]','["breakfast","winter","vegetarian"]','published',strftime('%s','now'),strftime('%s','now')),
('r-beet','beetroot-cutlet','Beetroot Cutlet','Colourful, nutritious and loved by kids.','img-beet',76,5,8,'4 PM Snack','Winter','Veg',25,'Medium','[{"name":"Beetroot","qty":"1 medium","key":"beetroot"},{"name":"Potato","qty":"2 medium","key":"potatoes"}]','[{"title":"Mix","text":"Combine cooked beetroot and potato with mild spices."},{"title":"Shape","text":"Form small cutlets."},{"title":"Cook","text":"Pan-cook until crisp."}]','{"calories":100,"protein":"2 g","fibre":"3 g"}','["Colourful","Vegetable-rich"]','["Yoghurt","Cucumber"]','["snack","winter","vegetarian"]','published',strftime('%s','now'),strftime('%s','now'));
